# 一、数据预处理

### 引入包

In [472]:
import datetime
import numpy as np
import pandas as pd

### 0、读取数据

In [502]:
train = pd.read_csv('data/train.csv', header=0)
test = pd.read_csv('data/test.csv', header=0)

In [503]:
X = train.iloc[:, :-1]
Y = train.iloc[:, -1]

In [ ]:
X.shape

In [ ]:
X_select.shape

In [230]:
X_result = X_drop_null.drop('Id', axis=1)

In [475]:
X.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [476]:
info_data = pd.read_excel('data/data_info_compare.xlsx', header=0)
info_data['train_null_num'] = train.shape[0] - info_data['train_total']
info_data['test_null_num'] = test.shape[0] - info_data['test_total']
rule_and = ((info_data['train_null_num'] > 0) & (info_data['train_null_num'] < 1000))
data1 = info_data.loc[rule_and, :]
# rule_or = ((info_data['train_null_num'] >1000) & (info_data['test_null_num'] >1000))
data1

,columns,train_data,test_data,train_total,test_total,train_null_num,test_null_num
3,LotFrontage,1201 non-null float64,1232 non-null float64,1201,1232.0,259,227.0
25,MasVnrType,1452 non-null object,1443 non-null object,1452,1443.0,8,16.0
26,MasVnrArea,1452 non-null float64,1444 non-null float64,1452,1444.0,8,15.0
30,BsmtQual,1423 non-null object,1415 non-null object,1423,1415.0,37,44.0
31,BsmtCond,1423 non-null object,1414 non-null object,1423,1414.0,37,45.0
32,BsmtExposure,1422 non-null object,1415 non-null object,1422,1415.0,38,44.0
33,BsmtFinType1,1423 non-null object,1417 non-null object,1423,1417.0,37,42.0
35,BsmtFinType2,1422 non-null object,1417 non-null object,1422,1417.0,38,42.0
42,Electrical,1459 non-null object,1459 non-null object,1459,1459.0,1,0.0
57,FireplaceQu,770 non-null object,729 non-null object,770,729.0,690,730.0
58,GarageType,1379 non-null object,1383 non-null object,1379,1383.0,81,76.0
59,GarageYrBlt,1379 non-null float64,1381 non-null float64,1379,1381.0,81,78.0
60,GarageFinish,1379 non-null object,1381 non-null object,1379,1381.0,81,78.0
63,GarageQual,1379 non-null object,1381 non-null object,1379,1381.0,81,78.0
64,GarageCond,1379 non-null object,1381 non-null object,1379,1381.0,81,78.0

### 1、删除列

In [477]:
# 删除Alley,PoolQC,Fence，MiscFeature (many null)
# 删除 Utilities (Many same values for train data,the same values for test data)
drop_col = ['Alley', 'PoolQC', 'Fence', 'MiscFeature', 'Utilities']
X.drop(drop_col, axis=1, inplace=True)
test.drop('Alley', axis=1, inplace=True)

In [478]:
# 考虑删除PoolArea，  many valuse is 0
# 3SsnPorch/EnclosedPorch   1200 左右是0 可以考虑是否删除
# MiscVal  1400 左右为0

### 2、类别型

BsmtFullBath: Basement full bathrooms <br>
地下室完整的浴室 4类别 数字 需要变为类型<br>


还需要处理的字段   BsmtHalfBath

In [479]:
# FullBath/HalfBath/BedroomAbvGr/KitchenAbvGr/TotRmsAbvGrd/Fireplaces/GarageCars

In [480]:
# 类别是数字表示的字段  MSSubClass/OverallQual/OverallCond/
columns_num_class = ['MSSubClass', 'OverallQual', 'OverallCond']

for cols in columns_num_class:
    X[cols] = X[cols].astype(str)
    test[cols] = test[cols].astype(str)

In [481]:
# X['enc_street'] = pd.get_dummies(X.Street, drop_first=True)
# test['enc_street'] = pd.get_dummies(test.Street, drop_first=True)

In [482]:
# def encode(x): return 1 if x == 'Partial' else 0
# X['enc_condition'] = X.SaleCondition.apply(encode)
# test['enc_condition'] = test.SaleCondition.apply(encode)

In [483]:
# train['enc_condition'] = train.SaleCondition.apply(encode)
# test['enc_condition'] = test.SaleCondition.apply(encode)

### 3、日期类型

日期字段 <br>
GarageYrBlt: Year garage was built<br>
车库建成 年份  有空值<br>
YearBuilt: Original construction date<br>
建造日期<br>
YearRemodAdd: Remodel date<br>
改建日期<br>

In [484]:
# 月销售与年销售  是日期
# YrSold
# MoSold

In [485]:
# 树模型里面日期不用转为object，直接使用数字
year_process_fun = lambda x: pd.datetime.strptime(str(x), '%Y').strftime('%Y')
month_process_fun = lambda x: pd.datetime.strptime(str(x), '%m').strftime('%m')

y_m_process_fun = lambda x: pd.datetime.strptime(str(x), '%Y%m').strftime('%Y-%m')

In [486]:
X['YearBuilt']  = X['YearBuilt'].astype(int).map(year_process_fun)
X['YearRemodAdd']  = X['YearRemodAdd'].astype(int).map(year_process_fun)
X['YrSold']  = X['YrSold'].astype(int).map(year_process_fun)

X['MoSold']  = (X['MoSold']).astype(int).map(month_process_fun)

# X['YMSold']  = (X['YrSold'] + X['MoSold']).map(y_m_process_fun)

In [487]:
test['YearBuilt']  = test['YearBuilt'].astype(int).map(year_process_fun)
test['YearRemodAdd']  = test['YearRemodAdd'].astype(int).map(year_process_fun)
test['YrSold']  = test['YrSold'].astype(int).map(year_process_fun)

test['MoSold']  = (test['MoSold']).astype(int).map(month_process_fun)

# test['YMSold']  = (test['YrSold'] + test['MoSold']).map(y_m_process_fun)

In [488]:
X.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,Inside,Gtl,...,61,0,0,0,0,0,02,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,FR2,Gtl,...,0,0,0,0,0,0,05,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,Inside,Gtl,...,42,0,0,0,0,0,09,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,Corner,Gtl,...,35,272,0,0,0,0,02,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,FR2,Gtl,...,84,0,0,0,0,0,12,2008,WD,Normal

In [489]:
# 填写为-1
X['GarageYrBlt'] = X['GarageYrBlt'].astype(str).fillna('-1')
test['GarageYrBlt'] = test['GarageYrBlt'].astype(str).fillna('-1')

### 4、空值处理

In [491]:
all_data = pd.concat((X.loc[:,'MSSubClass':'SaleCondition'], test.loc[:,'MSSubClass':'SaleCondition']))

In [500]:
train['n_null'] = (train<0).sum(axis=1)

In [501]:
train['n_null'].value_counts()

43    1460
Name: n_null, dtype: int64

In [499]:
X[X['n_null']>0] .head(20)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,n_null
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,Inside,Gtl,...,0,0,0,0,0,02,2008,WD,Normal,46
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,FR2,Gtl,...,0,0,0,0,0,05,2007,WD,Normal,46
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,Inside,Gtl,...,0,0,0,0,0,09,2008,WD,Normal,46
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,Corner,Gtl,...,272,0,0,0,0,02,2006,WD,Abnorml,46
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,46
5,6,50,RL,85.0,14115,Pave,IR1,Lvl,Inside,Gtl,...,0,320,0,0,700,10,2009,WD,Normal,46
6,7,20,RL,75.0,10084,Pave,Reg,Lvl,Inside,Gtl,...,0,0,0,0,0,08,2007,WD,Normal,46
7,8,60,RL,NaN,10382,Pave,IR1,Lvl,Corner,Gtl,...,228,0,0,0,350,11,2009,WD,Normal,46
8,9,50,RM,51.0,6120,Pave,Reg,Lvl,Inside,Gtl,...,205,0,0,0,0,04,2008,WD,Abnorml,46
9,10,190,RL,50.0,7420,Pave,Reg,Lvl,Corner,Gtl,...,0,0,0,0,0,01,2008,WD,Normal,46
10,11,20,RL,70.0,11200,Pave,Reg,Lvl,Inside,Gtl,...,0,0,0,0,0,02,2008,WD,Normal,46
11,12,60,RL,85.0,11924,Pave,IR1,Lvl,Inside,Gtl,...,0,0,0,0,0,07,2006,New,Partial,46
12,13,20,RL,NaN,12968,Pave,IR2,Lvl,Inside,Gtl,...,0,0,176,0,0,09,2008,WD,Normal,46
13,14,20,RL,91.0,10652,Pave,IR1,Lvl,Inside,Gtl,...,0,0,0,0,0,08,2007,New,Partial,46
14,15,20,RL,NaN,10920,Pave,IR1,Lvl,Corner,Gtl,...,176,0,0,0,0,05,2008,WD,Normal,46
15,16,45,RM,51.0,6120,Pave,Reg,Lvl,Corner,Gtl,...,0,0,0,0,0,07,2007,WD,Normal,46
16,17,20,RL,NaN,11241,Pave,IR1,Lvl,CulDSac,Gtl,...,0,0,0,0,700,03,2010,WD,Normal,46
17,18,90,RL,72.0,10791,Pave,Reg,Lvl,Inside,Gtl,...,0,0,0,0,500,10,2006,WD,Normal,46
18,19,20,RL,66.0,13695,Pave,Reg,Lvl,Inside,Gtl,...,0,0,0,0,0,06,2008,WD,Normal,46
19,20,20,RL,70.0,7560,Pave,Reg,Lvl,Inside,Gtl,...,0,0,0,0,0,05,2009,COD,Abnorml,46

In [ ]:
X_drop_null = X.select_dtypes(include=[np.number]).interpolate().dropna()
sum(X_drop_null.isnull().sum() != 0)

In [454]:
from scipy.stats import skew

In [455]:
numeric_feats = all_data.dtypes[all_data.dtypes != "object"].index
skewed_feats = X[numeric_feats].apply(lambda x: skew(x.dropna())) #compute skewness
skewed_feats = skewed_feats[skewed_feats > 0.75]
skewed_feats = skewed_feats.index
all_data[skewed_feats] = np.log1p(all_data[skewed_feats])
all_data = pd.get_dummies(all_data)
all_data = all_data.fillna(all_data.mean())
X = all_data[:X.shape[0]]
test_data = all_data[X.shape[0]:]

In [456]:
outlier_idx = [4,11,13,20,46,66,70,167,178,185,199, 224,261, 309,313,318, 349,412,423,440,454,477,478, 523,540, 581,588,595,654,688, 691, 774, 798, 875, 898,926,970,987,1027,1109, 1169,1182,1239, 1256,1298,1324,1353,1359,1405,1442,1447]
X.drop(X.index[outlier_idx],inplace=True)

D:\BigData\Python\Install\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [459]:
Y.drop(Y.index[outlier_idx],inplace=True)

In [458]:
X.shape

(1409, 600)

### 5、切分数据集

In [460]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=42, test_size=.33)

In [ ]:
Y = np.log1p(Y)

### 6、预测

In [461]:
from sklearn.ensemble import RandomForestRegressor

In [462]:
from sklearn.grid_search import GridSearchCV

In [463]:
from sklearn.metrics import make_scorer, mean_squared_error

In [464]:
def mean_squared_error_(ground_truth, predictions):
    return mean_squared_error(ground_truth, predictions) ** 0.5
RMSE = make_scorer(mean_squared_error_, greater_is_better=False)

In [465]:
rfr = RandomForestRegressor(n_jobs=1, random_state=0)
param_grid = {'n_estimators': [1500, 2000], 'max_features': [15,25,35], 'max_depth':[11,15,25]}
model = GridSearchCV(estimator=rfr, param_grid=param_grid, n_jobs=1, cv=10, scoring=RMSE)
model.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [1500, 2000], 'max_features': [15, 25, 35], 'max_depth': [11, 15, 25]},
       pre_dispatch='2*n_jobs', refit=True,
       scoring=make_scorer(mean_squared_error_, greater_is_better=False),
       verbose=0)

In [466]:
print('Random forecast regression...')
print('Best Params:')
print(model.best_params_)
print('Best CV Score:')
print(-model.best_score_)
score = -model.best_score_
y_pred = model.predict(test_data)

Random forecast regression...
Best Params:
{'max_depth': 25, 'max_features': 35, 'n_estimators': 2000}
Best CV Score:
0.14539268684751758

In [467]:

now = datetime.datetime.now()
sub_file = 'submission/submission_'+str(score)+'_'+str(now.strftime("%Y-%m-%d-%H-%M"))+'.csv'
print ('Creating submission: ', sub_file)
pd.DataFrame({'Id': test['Id'].values, 'SalePrice': np.exp(y_pred)}).to_csv(sub_file, index=False)

Creating submission:  submission/submission_0.14539268684751758_2018-04-13-23-12.csv